// @flow
export const TRANSITION_STATUS_UPDATED: 'TRANSITION_STATUS_UPDATED' = 'TRANSITION_STATUS_UPDATED';
export const STATE_REQUESTED: 'STATE_REQUESTED' = 'STATE_REQUESTED';
export const STATE_CHANGED: 'STATE_CHANGED' = 'STATE_CHANGED';
export const TRANSITION_STARTED: 'TRANSITION_STARTED' = 'TRANSITION_STARTED';
export const TRANSITION_FINISHED: 'TRANSITION_FINISHED' = 'TRANSITION_FINISHED';
